apiVersion: v1
kind: Service
metadata:
  name: dreamy-frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

spec:
  type: LoadBalancer

  selector:
    app: dreamy-frontend

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80